version: '3' # composeファイルのバーション指定
services:
  app: # service名
    container_name: go_api
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
    ports:
      - "1323:1323"
    depends_on:
      - mysql
  mysql:
        image: mysql:latest
        container_name: go_api_db
        environment:
          MYSQL_ROOT_PASSWORD: root-pass
          MYSQL_DATABASE: golang-test-database
          MYSQL_USER: golang-test-user
          MYSQL_PASSWORD: golang-test-pass
