version: '3' # composeファイルのバーション指定
services:
  app: # service名
    container_name: go_api
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
    ports:
      - "1323:1323"
    depends_on:
      - db
  db:
        image: postgres:latest
        container_name: go_api_db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - PGPASSWORD=password
          - POSTGRES_DB=testdb
          - DATABASE_HOST=localhost

          # MYSQL_ROOT_PASSWORD: root-pass
          # MYSQL_DATABASE: golang-test-database
          # MYSQL_USER: golang-test-user
          # MYSQL_PASSWORD: golang-test-pass
